networkservicemesh/integration-tests

.golangci.yml
gen.go
go.mod
go.sum
suites/basic/suite.gen.go
suites/spire/suite.gen.go

re-generate tests with latest gotestmd

---

.gitignore
gen.go
suites/basic/suite.gen.go
suites/memory/suite.gen.go
suites/sriov/suite.gen.go

Regenerates tests with SR-IOV kernel examples

Regenerate tests with SR-IOV kernel examples

---

.golangci.yml
extensions/base/suite.go
extensions/checkout/suite.go
go.mod
go.sum
suites/basic/suite.gen.go
suites/memory/suite.gen.go
suites/spire/suite.gen.go
suites/sriov/suite.gen.go

feat: Add checkout extension and re-genereate suites to latest gotestmd

---

.github/workflows/ci.yaml
.github/workflows/pr-for-updates.yaml
.github/workflows/update-dependent-repositories-gomod.yaml

This PR allows to repository integration-tests do updates to integration-k8s-kind.

feat: add update deps job for integration-tests

---

.github/workflows/ci.yaml

Fixes: https://github.com/networkservicemesh/integration-tests/pull/14/checks?check_run_id=1807441462

fix: automerge job is not working

---

extensions/base/suite.go
suites/basic/suite.gen.go
suites/memory/suite.gen.go

Re-generate suites manually due to https://github.com/networkservicemesh/gotestmd/issues/16

Re-generate suites manually

---

extensions/prefetch/ignore.go
extensions/prefetch/k8s.go
extensions/prefetch/sriov/sriov.go
extensions/prefetch/suite.go

fix: Docker images prefetch failing on kind

---

.github/workflows/automerge.yaml

Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>

fix err: 'fatal: couldn't find remote ref master' on automerge

---

go.mod
go.sum

Signed-off-by: Artem Glazychev <artem.glazychev@xored.com>

Manual gotestmd update

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
.github/workflows/update-dependent-repositories-gomod.yaml

Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>

feat: Add release actions

---

extensions/logs/logs.go

Fix: #694 
Example, what it looks like after this fix applying:
```
logs
├── TestRunBasicSuite
│   ├── admission-webhook-k8s-75b9d595fc-csrc6.logs
│   ├── forwarder-vpp-d8fgc.logs
│   ├── forwarder-vpp-mhvs5.logs
│   ├── nsmgr-mpw88.logs
│   ├── nsmgr-rqmpp.logs
│   ├── registry-k8s-758587b875-k842l.logs
│   └── TestMemif2Kernel
│       ├── admission-webhook-k8s-75b9d595fc-csrc6.logs
│       ├── forwarder-vpp-d8fgc.logs
│       ├── forwarder-vpp-mhvs5.logs
│       ├── nsc-memif-55b98fd85c-qg8t9.logs
│       ├── nse-kernel-597bd57585-m8zrx.logs
│       ├── nsmgr-mpw88.logs
│       ├── nsmgr-rqmpp.logs
│       └── registry-k8s-758587b875-k842l.logs
└── TestRunFeatureSuite
├── admission-webhook-k8s-75b9d595fc-vtz4l.logs
├── forwarder-vpp-m6d76.logs
├── forwarder-vpp-t928m.logs
├── …
```

Save logs from all pod containers

---

.github/workflows/automerge.yaml
.github/workflows/pr-for-updates.yaml
.github/workflows/update-dependent-repositories-gomod.yaml

Signed-off-by: Mikhail Avramenko <avramenkomihail15@gmail.com>
part of https://github.com/networkservicemesh/cmd-template/issues/64

Updated nsmbot message

---

extensions/logs/logs.go

Signed-off-by: denis-tingaikin <denis.tingajkin@xored.com>
Closes https://github.com/networkservicemesh/integration-tests/issues/738

fix: Add support for storing interdomain logs on ci

---

extensions/base/suite.go

Addition to: https://github.com/networkservicemesh/integration-tests/pull/1063
Signed-off-by: Artem Glazychev <artem.glazychev@xored.com>

[qfix] Manual checkout sha update

---

go.mod
go.sum

Signed-off-by: denis-tingaikin <denis.tingajkin@xored.com>

qfix: Update to latest gotestmd manually

---

extensions/base/suite.go
extensions/logs/logs.go

Signed-off-by: Mikhail Avramenko <avramenkomihail15@gmail.com>

Added describe for tests

---

extensions/base/suite.go
extensions/logs/logs.go

Signed-off-by: Mikhail Avramenko <avramenkomihail15@gmail.com>

hotfix for usage of shell runner

---

.github/workflows/release.yaml

Signed-off-by: denis-tingaikin <denis.tingajkin@xored.com>

qfix: Add kind testing on releasing

---

extensions/base/suite.go

Signed-off-by: denis-tingaikin <denis.tingajkin@xored.com>

qfix: Add condition to correctly work with releases

---

extensions/base/suite.go

Fixes https://github.com/networkservicemesh/integration-k8s-gke/actions/runs/1779061837

qfix: prefetch for releases is not correct

---

extensions/logs/logs.go

Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>
https://github.com/networkservicemesh/integration-k8s-aks/pull/217

Add logs for observability and spire namespaces

---

.github/workflows/update-dependent-repositories-gomod.yaml

Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>

Fix input parameter for update-dependent-repositories-gomod

---

extensions/logs/logs.go

Log collection has been tested in this CI run: https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/4804506237
https://github.com/networkservicemesh/integration-tests/issues/2706

Fix log collection in integration examples

---

extensions/base/suite.go
extensions/logs/logs.go
extensions/parallel/suite.go

https://github.com/networkservicemesh/integration-tests/issues/2769

Add function for launching suites in parallel

---

extensions/parallel/suite.go

https://github.com/networkservicemesh/integration-k8s-kind/pull/841

Fix data race in parallel tests

---

extensions/logs/logs.go

https://github.com/networkservicemesh/deployments-k8s/issues/11229
Add docker container logs to build artifacts

Include docker logs.

---

extensions/prefetch/k8s.go

Issue: https://github.com/networkservicemesh/integration-tests/issues/3390
Updated images can work with both amd64 and arm64

Fix prefetch for ARM64

---

.github/workflows/release.yaml

https://github.com/networkservicemesh/deployments-k8s/issues/12681

Remove unsupported integration tests from workflows

---

.github/dependabot.yml

This PR enables Dependabot in the repository to automatically check GitHub Actions versions weekly and create pull requests for any outdated dependencies found.

Enable dependabot for updating github actions

---

.github/workflows/automerge.yaml
.github/workflows/update-dependent-repositories-gomod.yaml

This PR updates the automerge workflow to also allow pull requests opened by Dependabot.

Adjust accepted actors of automerge workflow
